apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nhuebers99-poi-map-app-dev
  annotations:
    argocd/app-name: nhuebers99-poi-map-app-dev
    backstage.io/kubernetes-id: nhuebers99-poi-map-app
    backstage.io/kubernetes-namespace: nhuebers99
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/nhuebers99-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/nhuebers99/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/nhuebers99/deployments/nhuebers99-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/nhuebers99-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://nhuebers99-poi-map-app-nhuebers99.apps.rosa-pzz6v.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/nhuebers99"
  system: workshop-system-nhuebers99
  consumesApis:
    - gateway-api-nhuebers99
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-nhuebers99
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/nhuebers99"
